sudo: required
language: generic

services:
  - docker

env:
  global:
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1

before_install:
  - whoami
  #- docker build -t pateldhiren494/react-test -f ./client/Dockerfile.dev ./client

script:
  #- docker run -e CI=true pateldhiren494/react-test npm test

install:
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project multi-k8s-329103
  - gcloud config set compute/zone us-east1-b
  - gcloud container clusters get-credentials multi-k8s


after_success:
  #- docker build -t pateldhiren494/multi-client ./client
  #- docker build -t pateldhiren494/multi-server ./server
  #- docker build -t pateldhiren494/multi-worker ./worker

  # Log in to the docker CLI
  #- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take those images and push them to docker hub
  #- docker push pateldhiren494/multi-client
  #- docker push pateldhiren494/multi-server
  #- docker push pateldhiren494/multi-worker

  - kubectl get nodes
  - kubectl apply -f ./k8s
