sudo: required
language: generic

services:
  - docker

before_install:
  - whoami
  #- docker build -t pateldhiren494/react-test -f ./client/Dockerfile.dev ./client

script:
  #- docker run -e CI=true pateldhiren494/react-test npm test

install: 
  - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
  - chmod +x ./kubectl
  - sudo mv ./kubectl /usr/local/bin/kubectl
  - curl -SL --insecure https://clis.cloud.ibm.com/install/linux > ibmcloudcli.sh
  - chown travis ibmcloudcli.sh
  - chmod +x ibmcloudcli.sh
  - cat ibmcloudcli.sh
  - sh ibmcloudcli.sh
  - ibmcloud plugin install container-service

after_success:
  - ibmcloud help
  - docker build -t pateldhiren494/multi-client ./client
  - docker build -t pateldhiren494/multi-server ./server
  - docker build -t pateldhiren494/multi-worker ./worker

  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take those images and push them to docker hub
  - docker push pateldhiren494/multi-client
  - docker push pateldhiren494/multi-server
  - docker push pateldhiren494/multi-worker

  #Deploying on ibm cloud
  - ibmcloud login --apikey "$IBMCLOUD_ACCESS_APIKEY"
  - ibmcloud ks cluster config --cluster multi-k8s --admin
  - kubectl get nodes
  - kubectl get pods
  - ls 
  - kubectl apply -f ./k8s
